from __future__ import annotations

from pathlib import Path

import pandas as pd

try:
    import plotly.express as px
except Exception:  # pragma: no cover
    px = None


def _write_html_fallback(title: str, frames: list[tuple[str, pd.DataFrame]], output_path: Path) -> Path:
    sections = []
    for name, frame in frames:
        sections.append(f"<h2>{name}</h2>{frame.to_html(index=False)}")

    html = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
    <style>
      body {{ font-family: Arial, sans-serif; margin: 24px; color: #1f2937; }}
      table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; }}
      th, td {{ border: 1px solid #e5e7eb; padding: 8px; text-align: left; }}
      th {{ background: #f9fafb; }}
      h1 {{ margin-bottom: 4px; }}
      p {{ color: #4b5563; }}
    </style>
  </head>
  <body>
    <h1>{title}</h1>
    <p>Generated by AgriX analytics pipeline.</p>
    {''.join(sections)}
  </body>
</html>"""
    output_path.write_text(html, encoding="utf-8")
    return output_path


def build_productivity_trends_dashboard(trends_df: pd.DataFrame, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if px is None:
        return _write_html_fallback("Crop Productivity Trends Dashboard", [("Productivity Trends", trends_df)], output_path)

    fig = px.line(
        trends_df,
        x="date",
        y="avg_yield_tph",
        color="region_id",
        title="Crop Productivity Trends (Yield per Hectare)",
        markers=True,
    )
    fig.update_layout(template="plotly_white", xaxis_title="Date", yaxis_title="Average Yield (t/ha)")
    fig.write_html(str(output_path), include_plotlyjs="cdn")
    return output_path


def build_rainfall_correlation_dashboard(observations_df: pd.DataFrame, correlation_df: pd.DataFrame, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if px is None:
        return _write_html_fallback(
            "Rainfall Correlation Dashboard",
            [("Rainfall vs Yield Observations", observations_df), ("Correlation Summary", correlation_df)],
            output_path,
        )

    fig = px.scatter(
        observations_df,
        x="rainfall_mm",
        y="yield_tph",
        color="region_id",
        title="Rainfall Correlation with Crop Yield",
        hover_data=["date", "crop"],
    )
    fig.update_layout(template="plotly_white", xaxis_title="Rainfall (mm)", yaxis_title="Yield (t/ha)")
    fig.write_html(str(output_path), include_plotlyjs="cdn")
    return output_path


def build_climate_impact_dashboard(climate_impact_df: pd.DataFrame, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if px is None:
        return _write_html_fallback("Climate Impact Dashboard", [("Climate Impact Analysis", climate_impact_df)], output_path)

    y_col = "avg_yield_tph" if "avg_yield_tph" in climate_impact_df.columns else "yield_tph"
    fig = px.scatter(
        climate_impact_df,
        x="temperature_c",
        y=y_col,
        color="climate_stress_level",
        size="climate_stress_index",
        hover_data=["region_id", "date", "rainfall_mm", "rainfall_anomaly", "temperature_anomaly"],
        title="Climate Impact on Crop Productivity",
    )
    fig.update_layout(template="plotly_white", xaxis_title="Temperature (C)", yaxis_title="Average Yield (t/ha)")
    fig.write_html(str(output_path), include_plotlyjs="cdn")
    return output_path
